services:
  - type: web
    name: rebhi-server
    runtime: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/src/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true